language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database dummy_qc_admin_test;' -U postgres
  - "bundle exec rake db:schema:load RAILS_ENV=test"
  - "bundle exec rake db:migrate RAILS_ENV=test"
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
